editor:
  - 'create content translations'
  - 'delete content translations'
  - 'translate block_content'
  - 'translate interface'
  - 'translate menu_link_content'
  - 'translate page node'
  - 'translate paragraph'
  - 'update content translations'
site_manager:
  - 'create content translations'
  - 'delete content translations'
  - 'translate any entity'
  - 'translate block_content'
  - 'translate interface'
  - 'translate menu_link_content'
  - 'translate page node'
  - 'translate paragraph'
  - 'update content translations'
