<?php

/**
 * @file
 * Install, update and uninstall functions for the A12S Factory profile.
 */

include "includes/install.inc";

use Drupal\user\Entity\User;
use Drupal\user\UserInterface;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function a12sfactory_install(): void {
  // Set the front page to "node".
  \Drupal::configFactory()->getEditable('system.site')->set('page.front', '/node')->save(TRUE);

  // Restrict user registration to admin role creation.
  \Drupal::configFactory()->getEditable('user.settings')->set('register', UserInterface::REGISTER_ADMINISTRATORS_ONLY)->save(TRUE);

  // Assign user 1 the "administrator" role.
  /** @var UserInterface $user */
  $user = User::load(1);
  $user->addRole('administrator');
  $user->save();

  // Use the admin theme on node edit pages.
  \Drupal::configFactory()->getEditable('node.settings')->set('use_admin_theme', TRUE)->save(TRUE);
}

/**
 * Return the last hook_update_N() number.
 *
 * @return int
 *
 * @see \hook_update_last_removed()
 */
function a12sfactory_update_last_removed(): int {
  return 8013;
}
