version: "3.5"

services:
  php:
    container_name: ${PROJECT_NAME}_php
    image: docker.a12s.io/aion-solutions/container-images/php-8.0:8.0.3-xdebug-r3
    environment:
      APP_URL: $PROJECT_NAME.a12s.local
      PHP_IDE_CONFIG: serverName=$PROJECT_NAME-server
      XDEBUG_CONFIG: client_host=10.211.55.2 # On host => ifconfig |grep 10.211.55|cut -d" " -f2
      DATABASE_NAME: $PROJECT_NAME
      DATABASE_DRIVER: mysql
      DATABASE_HOST: mariadb
      DATABASE_USER: root
      DATABASE_PASSWORD: dev
      DATABASE_PORT: 3306
      SMTP_TRANSPORT: smtp
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      APP_ENV: local
      APP_SCHEME: https://
    volumes:
      - .:/app
      - ../public/:/app/web/sites/default/files
      - ../private/:/app/private
      - ./local/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      - /home/aion/projects/development-toolbox/file/traefik-db/config/a12s.local.pem:/usr/local/share/ca-certificates/a12s.local.pem
    labels:
      - traefik.enable=false
    entrypoint: /bin/sh -c "apk add --no-cache ca-certificates && update-ca-certificates && php-fpm"
    extra_hosts:
      - "$PROJECT_NAME.a12s.local:172.18.0.1"
    networks:
      - a12s-local

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:1.21-alpine
    env_file:
      - .env
    links:
      - php
    volumes:
      - .:/app
      - ../public/:/app/web/sites/default/files
      - ../private/:/app/private
      - ./local/nginx.conf:/etc/nginx/nginx.conf.template:ro
    command: /bin/sh -c "envsubst '$$PROJECT_NAME'< /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    labels:
      - traefik.http.services.app-$PROJECT_NAME.loadbalancer.server.port=8000
      - traefik.http.routers.app-$PROJECT_NAME-https.rule=Host(`$PROJECT_NAME.a12s.local`)
      - traefik.http.routers.app-$PROJECT_NAME-https.tls=true
    networks:
      - a12s-local

networks:
  a12s-local:
    external: true
