name: "Security Recipe"
description: "Security configuration with honeypot"
type: "drupal-recipe"
install:
  - password_policy:password_policy
  - password_policy:password_policy_length
  - password_policy:password_policy_username
config:
  import:
    password_policy:
      - password_policy.password_policy.default.yml
  strict: false
  actions:
    user.role.site_manager:
      ensure_exists:
        id: site_manager
      grantPermissions:
        - "administer password_policy"
